### ISSUE TITLE
How to interact with Pi Game

### ISSUE THREAD

**Issue by Wippers** [makeTVee/ledmatrix#3]
Thanks for this greatr project!

I am trying to use it and I am struggling with an issue.
When I run the project in simulation mode (Pi = False) , Pi Game does launch and displays current time but I cannot do anything else.

I am keying  on keyboard 1,2 3,4, S or X, but Pi game does react and continues to display time.

What should I do to have the keyboard taken into account?

Thanks

**Comment by makeTVee** [comment]
Hi!
Normally, "4" should switch the screen. Tested it here and it works. 
Which OS are you using? Can you click into the display to ensure, that the display has the focus? If you can provide me some more details about your platform, I can try to reproduce the issue.
Best
maketvee

**Comment by Wippers** [comment]
Thank you very much for taking the time to answer.

I am using Pycharm CE and Windows 10.
I have found the issue, I was running games_pi instead of games_pi_only.

I am new to this dev platform and language, and learning by hit and miss ;)
Thanks again for your help
